[package]
name = "rah-sandbox"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["process", "time"] }

[dev-dependencies]
futures.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
