[package]
name = "rah-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rah"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
rah-model = { path = "../rah-model" }
rah-protocol = { path = "../rah-protocol" }
rah-runtime = { path = "../rah-runtime" }
rah-tools = { path = "../rah-tools" }
rah-tools-mcp = { path = "../rah-tools-mcp" }
rah-tools-plugin = { path = "../rah-tools-plugin" }
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "time"] }
tracing-subscriber.workspace = true
