"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");

const source = fs.readFileSync(`${__dirname}/status.js`, "utf8");
const html = fs.readFileSync(`${__dirname}/index.html`, "utf8");

assert.match(html, /id="repository-member-selector"/);
assert.match(html, /id="activate-repository-member"/);
assert.match(html, /id="remove-repository-member"/);
assert.match(html, /id="repository-member-removal-confirmation"/);
assert.match(html, /This removes only the current process-local workspace membership\. Repository files will not be deleted, and any remembered workspace entry will remain\./);
assert.match(source, /invoke\("repository_membership"\)/);
assert.match(source, /invoke\("activate_repository_member", \{ memberId: selector\.value \}\)/);
assert.match(source, /function renderRepositoryMembership\(/);
assert.match(source, /\(\$\{member\.active === true \? "Active" : "Inactive"\}\)/);
assert.match(source, /removeButton\.disabled = !selectedMember \|\| selectedIsActive/);
assert.match(source, /Switch to another repository before removing this active repository\./);
assert.match(source, /function installRepositoryMemberRemovalHandler\(/);
assert.match(source, /confirmation\.showModal\(\)/);
assert.match(source, /function removeRepositoryMember\(invoke, memberId\)/);
assert.match(source, /invoke\("remove_repository_member", \{ memberId \}\)/);
assert.match(source, /renderRepositoryMembership\(result\.membership\)/);
assert.match(source, /Repository removed from current workspace\./);
assert.match(source, /This repository is no longer in the current workspace\./);
assert.match(source, /This repository cannot be removed while related repository work is still in progress\./);
assert.match(source, /confirmation\.returnValue !== "confirm" \|\| !memberId/);
assert.match(source, /renderRepositoryMembership\(result\.membership\)/);
assert.match(source, /result\.outcome === "activated"/);
assert.match(source, /selected === active/);
assert.match(source, /repositorySwitchBlocked/);
assert.match(source, /repository_member_selector_invalid/);
assert.match(source, /repository_member_not_found/);
assert.match(source, /repository_member_stale/);
assert.equal(source.includes("nativePath"), false);
assert.equal(source.includes("RepositoryAdmissionIdentity"), false);
assert.equal(source.includes("ToolRegistry"), false);
assert.equal(source.includes("repository_id"), false);
assert.equal(source.includes("invoke(\"activate_repository_member\", { path"), false);
assert.equal(source.includes("invoke(\"activate_repository_member\", { repository"), false);
const removalHandler = source.slice(source.indexOf("function installRepositoryMemberRemovalHandler"), source.indexOf("function rememberedCandidateById"));
assert.equal(removalHandler.includes("activate_repository_member"), false);
assert.equal(removalHandler.includes("delete_remembered_workspace_candidate"), false);
assert.equal(removalHandler.includes("choose_repository"), false);
assert.equal(removalHandler.includes("admit_remembered_workspace_candidate"), false);
assert.equal(removalHandler.includes("repository_snapshot"), false);
assert.equal(removalHandler.includes("send_chat"), false);
assert.equal(removalHandler.includes("connect_codex"), false);
assert.equal(removalHandler.includes("localStorage"), false);
assert.equal(removalHandler.includes("sessionStorage"), false);
assert.equal(removalHandler.includes("innerHTML"), false);
const removalFunction = source.slice(source.indexOf("async function removeRepositoryMember"), source.indexOf("function installRepositoryMemberRemovalHandler"));
assert.match(removalFunction, /invoke\("remove_repository_member", \{ memberId \}\)/);
assert.equal(removalFunction.includes("path"), false);
assert.equal(removalFunction.includes("displayName"), false);
assert.match(source, /selector\.disabled = false/);
assert.equal(source.includes("delete_repository"), false);
assert.equal(source.includes("delete_repository_files"), false);

console.log("repository membership frontend tests passed");
