"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");

const root = __dirname;
const buildManifest = fs.readFileSync(`${root}/build.rs`, "utf8");
const desktopMain = fs.readFileSync(`${root}/src/main.rs`, "utf8");
const generatedPermission = fs.readFileSync(`${root}/permissions/autogenerated/host_prepare_repo_rename_file.toml`, "utf8");
const membershipPermission = fs.readFileSync(`${root}/permissions/autogenerated/repository_membership.toml`, "utf8");
const removeMemberPermission = fs.readFileSync(`${root}/permissions/autogenerated/remove_repository_member.toml`, "utf8");
const activateMemberPermission = fs.readFileSync(`${root}/permissions/autogenerated/activate_repository_member.toml`, "utf8");
const closeRepositoryPermission = fs.readFileSync(`${root}/permissions/autogenerated/close_repository.toml`, "utf8");
const capability = JSON.parse(fs.readFileSync(`${root}/capabilities/default.json`, "utf8"));
const permissions = capability.permissions;

assert.deepEqual(permissions, [
  "core:event:allow-listen",
  "core:event:allow-unlisten",
  "allow-app-status",
  "allow-trusted-profile-selection",
  "allow-choose-trusted-profile",
  "allow-restore-trusted-profile",
  "allow-forget-trusted-profile",
  "allow-clear-trusted-profile",
  "allow-model-configuration",
  "allow-set-model-configuration",
  "allow-reset-model-preferences",
  "allow-commit-identity",
  "allow-set-commit-identity",
  "allow-desktop-preferences-warning",
  "allow-test-llama-cpp-endpoint",
  "allow-choose-repository",
  "allow-remembered-workspace-catalog",
  "allow-reveal-remembered-workspace-location",
  "allow-remember-workspace-candidate",
  "allow-update-remembered-workspace-candidate",
  "allow-delete-remembered-workspace-candidate",
  "allow-reorder-remembered-workspace-candidates",
  "allow-admit-remembered-workspace-candidate",
  "allow-repository-membership",
  "allow-remove-repository-member",
  "allow-activate-repository-member",
  "allow-close-repository",
  "allow-connect-codex",
  "allow-disconnect-codex",
  "allow-repository-snapshot",
  "allow-repository-authorize-commit-review",
  "allow-repository-stage-action",
  "allow-repository-unstage-action",
  "allow-send-chat",
  "allow-cancel-chat",
  "allow-new-conversation",
  "allow-clear-conversation-history",
  "allow-resume-previous-conversation",
  "allow-conversation-transcript",
  "allow-get-effective-authority-snapshot",
  "allow-host-invoke-read",
  "allow-host-prepare-repo-create-branch",
  "allow-host-prepare-repo-patch",
  "allow-host-prepare-repo-rename-file",
  "allow-host-confirm-tool-invocation",
  "allow-host-cancel-tool-invocation",
]);

assert.equal((buildManifest.match(/"host_prepare_repo_rename_file"/g) ?? []).length, 1);
assert.match(buildManifest, /AppManifest::new\(\)\.commands\(&\[/);
assert.match(generatedPermission, /identifier = "allow-host-prepare-repo-rename-file"/);
assert.match(generatedPermission, /commands\.allow = \["host_prepare_repo_rename_file"\]/);
assert.match(generatedPermission, /identifier = "deny-host-prepare-repo-rename-file"/);
assert.deepEqual(permissions.filter((permission) => permission === "allow-host-prepare-repo-rename-file"), [
  "allow-host-prepare-repo-rename-file",
]);
assert.equal(permissions.some((permission) => /(^|:|-)fs($|:|-)/i.test(permission)), false);
assert.equal(permissions.some((permission) => permission.includes("host-prepare-repo-rename-file-*")), false);
assert.match(buildManifest, /"host_confirm_tool_invocation"/);
assert.match(buildManifest, /"host_cancel_tool_invocation"/);
assert.equal((buildManifest.match(/"repository_membership"/g) ?? []).length, 1);
assert.equal((buildManifest.match(/"remove_repository_member"/g) ?? []).length, 1);
assert.equal((buildManifest.match(/"activate_repository_member"/g) ?? []).length, 1);
assert.equal((buildManifest.match(/"close_repository"/g) ?? []).length, 1);
const handler = desktopMain.match(/\.invoke_handler\(tauri::generate_handler!\[([\s\S]*?)\]\)/)?.[1];
assert.ok(handler, "the Desktop Tauri handler should be registered");
assert.equal((handler.match(/^\s*close_repository,\s*$/gm) ?? []).length, 1);
assert.match(membershipPermission, /identifier = "allow-repository-membership"/);
assert.match(membershipPermission, /commands\.allow = \["repository_membership"\]/);
assert.match(removeMemberPermission, /identifier = "allow-remove-repository-member"/);
assert.match(removeMemberPermission, /commands\.allow = \["remove_repository_member"\]/);
assert.match(removeMemberPermission, /identifier = "deny-remove-repository-member"/);
assert.deepEqual(permissions.filter((permission) => permission === "allow-remove-repository-member"), [
  "allow-remove-repository-member",
]);
assert.equal(permissions.some((permission) => permission.includes("*")), false);
assert.deepEqual(
  permissions.filter((permission) => permission === "allow-repository-membership" || permission.includes("repository-member")),
  [
    "allow-repository-membership",
    "allow-remove-repository-member",
    "allow-activate-repository-member",
  ],
);
assert.match(activateMemberPermission, /identifier = "allow-activate-repository-member"/);
assert.match(activateMemberPermission, /commands\.allow = \["activate_repository_member"\]/);
assert.match(closeRepositoryPermission, /identifier = "allow-close-repository"/);
assert.match(closeRepositoryPermission, /commands\.allow = \["close_repository"\]/);
assert.match(closeRepositoryPermission, /identifier = "deny-close-repository"/);
assert.deepEqual(permissions.filter((permission) => permission === "allow-close-repository"), [
  "allow-close-repository",
]);
assert.deepEqual(permissions.filter((permission) => permission === "allow-repository-membership"), [
  "allow-repository-membership",
]);
assert.deepEqual(permissions.filter((permission) => permission === "allow-activate-repository-member"), [
  "allow-activate-repository-member",
]);
assert.deepEqual(permissions.filter((permission) => permission.startsWith("allow-host-confirm-tool-invocation")), [
  "allow-host-confirm-tool-invocation",
]);
assert.deepEqual(permissions.filter((permission) => permission.startsWith("allow-host-cancel-tool-invocation")), [
  "allow-host-cancel-tool-invocation",
]);
assert.equal(permissions.some((permission) => permission.includes("*")), false);

console.log("Tauri permission tests passed");
