"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");

const root = __dirname;
const buildManifest = fs.readFileSync(`${root}/build.rs`, "utf8");
const generatedPermission = fs.readFileSync(`${root}/permissions/autogenerated/host_prepare_repo_rename_file.toml`, "utf8");
const membershipPermission = fs.readFileSync(`${root}/permissions/autogenerated/repository_membership.toml`, "utf8");
const activateMemberPermission = fs.readFileSync(`${root}/permissions/autogenerated/activate_repository_member.toml`, "utf8");
const capability = JSON.parse(fs.readFileSync(`${root}/capabilities/default.json`, "utf8"));
const permissions = capability.permissions;

assert.equal((buildManifest.match(/"host_prepare_repo_rename_file"/g) ?? []).length, 1);
assert.match(buildManifest, /AppManifest::new\(\)\.commands\(&\[/);
assert.match(generatedPermission, /identifier = "allow-host-prepare-repo-rename-file"/);
assert.match(generatedPermission, /commands\.allow = \["host_prepare_repo_rename_file"\]/);
assert.match(generatedPermission, /identifier = "deny-host-prepare-repo-rename-file"/);
assert.deepEqual(permissions.filter((permission) => permission === "allow-host-prepare-repo-rename-file"), [
  "allow-host-prepare-repo-rename-file",
]);
assert.equal(permissions.some((permission) => /(^|:|-)fs($|:|-)/i.test(permission)), false);
assert.equal(permissions.some((permission) => permission.includes("host-prepare-repo-rename-file-*")), false);
assert.match(buildManifest, /"host_confirm_tool_invocation"/);
assert.match(buildManifest, /"host_cancel_tool_invocation"/);
assert.equal((buildManifest.match(/"repository_membership"/g) ?? []).length, 1);
assert.equal((buildManifest.match(/"activate_repository_member"/g) ?? []).length, 1);
assert.match(membershipPermission, /identifier = "allow-repository-membership"/);
assert.match(membershipPermission, /commands\.allow = \["repository_membership"\]/);
assert.match(activateMemberPermission, /identifier = "allow-activate-repository-member"/);
assert.match(activateMemberPermission, /commands\.allow = \["activate_repository_member"\]/);
assert.deepEqual(permissions.filter((permission) => permission === "allow-repository-membership"), [
  "allow-repository-membership",
]);
assert.deepEqual(permissions.filter((permission) => permission === "allow-activate-repository-member"), [
  "allow-activate-repository-member",
]);
assert.deepEqual(permissions.filter((permission) => permission.startsWith("allow-host-confirm-tool-invocation")), [
  "allow-host-confirm-tool-invocation",
]);
assert.deepEqual(permissions.filter((permission) => permission.startsWith("allow-host-cancel-tool-invocation")), [
  "allow-host-cancel-tool-invocation",
]);

console.log("Tauri rename permission tests passed");
